function [scenarioName] = ExportJSON(SceStr,SimInfo,ObjAircraft,TFC,EC,Settings)
M = SimInfo.M(end);
full_pdt = full(SimInfo.pdt)';
full_stat = full(SimInfo.statusdt)';
ObjAircraftData = cell(1, M);
for i = 1:M
    x = double(full_pdt(3*i-2, :));
    y = double(full_pdt(3*i-1, :));
    z = double(full_pdt(3*i, :));
    stat = double(full_stat(i, :));
    ObjAircraftData{i} = struct(...
    'stat', stat,...
    'tda',max(ObjAircraft(i).tdp,0),...
    'taa',min(ObjAircraft(i).taa,SimInfo.tf),...
    'rs',ObjAircraft(i).rs,...
    'rd',ObjAircraft(i).rd,...
    'x', x,...
    'y', y,...
    'z', z...
    );
end
json_data = struct(...
'ObjAircraft', ObjAircraftData,...
'tf', SimInfo.tf,...
'dtS', SimInfo.dtS,...
'dtM', SimInfo.dtM,...
'dx', Settings.Airspace.dx,...
'dy', Settings.Airspace.dy,...
'dz', Settings.Airspace.dz...
);
json_str = jsonencode(json_data);
TimestampNow = now;
scenarioName = [SceStr ' '  datestr(TimestampNow,'yyyy-mm-dd HH:MM')];
file_name = ['./public/Outputs/' 'SimOutput_' SceStr '_'  datestr(TimestampNow,'yyyymmdd_hhMM') '.json']; % datestr(now,'yyyymmdd_hhMMss')
fid = fopen(file_name, 'w');
if fid > 0
    fwrite(fid, json_str, 'char');
    fclose(fid);
    disp(['Data saved to ' file_name]);
else
    disp('Error opening the file for writing.');
end
end


